In [108]:
import numpy as np
import math

def TPS_F( i , j ):
  if abs( i - j ) == 1 :
    return  (y[i] - y[j]) / (x[i] - x[j])
  else :
    return ( TPS_F(i + 1 , j) - TPS_F(i , j - 1 ) ) / (x[j] - x[i])
  

def TPS_B ( i , j ):
  if abs( i - j ) == 1 :
    return  (y[j] - y[i])
  else :
    return TPS_B(i + 1 , j) - TPS_B(i , j - 1 ) 
  

In [164]:
# x = [3.2 , 3.5 , 3.7 , 3.8 , 4.1]
# y = [30.3222 , 40.5807 , 48.5752 , 52.9341 , 67.5127]

# x = [1.3 , 1.6 , 1.8 , 2]
# y = [4.1825 , 5.0324 , 5.7984 , 6.7516]

x = [1.2 , 1.4 , 1.6  , 1.8 , 2 , 2.2]
y = [2.6158  , 3.1604 , 4.0245 , 5.2754 , 6.9804 , 9.2062]

n = len(x)
x = np.array(x)
def Forward_Different():
  forward_vector = [y[0]]
  for step in range(1, n ):
    forward_vector.append(TPS_F(0 , step))
  return(np.array(forward_vector))

def Backward_Different():
  backward_vector = [y[0]]
  for step in range(1, n ):
    backward_vector.append(TPS_B(0 , step) / math.factorial(step ))
  return(np.array(backward_vector))

Backward_Different()

array([ 2.61580000e+00,  5.44600000e-01,  1.59750000e-01,  1.12166667e-02,
       -1.11022302e-16, -5.00000000e-06])

In [165]:
x_iterator = np.arange(n - 1)
print(x_iterator)

def Different_Table(x = x):
  matrix_multi = np.zeros((n  , n ))
  matrix_multi[1: , 0] = -x[:n-1]
  matrix_multi[1: , 1] = 1
  matrix_multi[0 , 0] = 1
  for row in range(2 , n, 1):
    temp = np.zeros(n)
    for i in range(n):
      for j in range(n - i):
        temp[i+j] += matrix_multi[row - 1][i] * matrix_multi[row][j]
    matrix_multi[row] = temp

  matrix_multi = matrix_multi[: , ::-1]
  return matrix_multi


Different_Table(x = x_iterator)

[0 1 2 3 4]


array([[  0.,   0.,   0.,   0.,   0.,   1.],
       [  0.,   0.,   0.,   0.,   1.,   0.],
       [  0.,   0.,   0.,   1.,  -1.,   0.],
       [  0.,   0.,   1.,  -3.,   2.,   0.],
       [  0.,   1.,  -6.,  11.,  -6.,   0.],
       [  1., -10.,  35., -50.,  24.,   0.]])

In [166]:
def Compute_result_vector_forward():
    print(f"Vector ti phan sai : \n {Forward_Different()} ")
    print(f"Ma tran tich : \n {Different_Table()}")
    print(f"Ket qua he so bat dau tu x^n-1 : \n {(Forward_Different().T * Different_Table().T).T.sum(axis= 0)}")

def Compute_result_vector_backward():
    print(f"Vector ti phan sai : \n {Backward_Different()} ")
    print(f"Ma tran tich : \n {Different_Table(x = x_iterator)}")
    print(f"Ket qua he so bat dau tu x^n-1 : \n {(Backward_Different().T * Different_Table(x = x_iterator).T).T.sum(axis= 0)}")

def get_result_backward():
    return (Backward_Different().T * Different_Table(x = x_iterator).T).T.sum(axis= 0)

def get_result_forward():
    return (Forward_Different().T * Different_Table().T).T.sum(axis= 0)


In [169]:
def compute_value_backward( x_value) :
    func = get_result_backward()
    n = len(func)
    sum = 0
    for i  in range(n):
        sum += func[i] * pow(x_value , n - i - 1)
    return sum 

def compute_value_backward_grad( x_value) :
    func = get_result_backward()
    n = len(func)
    sum = 0
    for i  in range( n - 1):
        sum += func[i] * pow(x_value , n - i - 2) * (n - i - 1)
    return sum/(abs(x[0] - x[1]))

def compute_value_forward( x_value) :
    func = get_result_forward()
    n = len(func)
    sum = 0
    for i  in range(n):
        sum += func[i] * pow(x_value , n - i - 1)
    return sum 

def compute_value_forward_grad( x_value) :
    func = get_result_forward()
    n = len(func)
    sum = 0
    for i  in range(n - 1):
        sum += func[i] * pow(x_value , n - i - 2) * (n - i - 1)
        print(func[i])
    return sum

compute_value_backward(2.5)


4.59738671875